In [87]:
from sklearn.neighbors import KNeighborsClassifier					
import pandas as pd 
import numpy as np			

dataset = pd.read_csv ('/Users/farrelmanazilin/Downloads/data/ruspini.csv')	
train_data = np.array(dataset)[ :, 1:-1]					
train_label = np.array(dataset)[:, -1]

kNN = KNeighborsClassifier(n_neighbors=3, weights= 'distance')
kNN.fit(train_data, train_label)
dataset

#   X   Y  CLASS
0    1   4  53      1
1    2   5  63      1
2    3  10  59      1
3    4   9  77      1
4    5  13  49      1
..  ..  ..  ..    ...
70  71  66  23      4
71  72  61  25      4
72  73  76  27      4
73  74  72  31      4
74  75  64  30      4

[75 rows x 4 columns]

In [88]:
angkaX = input('Tulis input X: ')
angkaY = input('Tulis input Y: ')
test_data= np.array([int(angkaX),int(angkaY)])					
print(test_data)		

Tulis input X: 123
Tulis input Y: 123
[123 123]


In [90]:
test_data = np.reshape(test_data, (1, -1))					
print(test_data)					
hasil= kNN.predict(test_data)					
print("Hasil dari k-NN : ", hasil)					

[[123 123]]
Hasil dari k-NN :  [2]


In [91]:
kNN =KNeighborsClassifier(n_neighbors=3, weights='distance')					
kNN.fit(train_data, train_label)					
hasil2= kNN.predict(test_data) 
print("Test Label : ", train_label) 
print ("Hasil kNN :", hasil2)					

Test Label :  [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4]
Hasil kNN : [2]


In [7]:
from sklearn.preprocessing import MinMaxScaler				
dataset = pd.read_csv('/Users/farrelmanazilin/Downloads/data/ruspini.csv')					
sc = MinMaxScaler(feature_range= (0, 1))
train_data = np .array(dataset)[:,1:-1] 
data = sc.fit_transform(train_data) 
print(data)					


[[0.         0.32236842]
 [0.00884956 0.38815789]
 [0.05309735 0.36184211]
 [0.04424779 0.48026316]
 [0.07964602 0.29605263]
 [0.07964602 0.42763158]
 [0.07079646 0.55263158]
 [0.09734513 0.46710526]
 [0.12389381 0.375     ]
 [0.13274336 0.40131579]
 [0.15929204 0.46052632]
 [0.20353982 0.44736842]
 [0.21238938 0.47368421]
 [0.17699115 0.35526316]
 [0.20353982 0.33552632]
 [0.21238938 0.36842105]
 [0.2300885  0.31578947]
 [0.23893805 0.36842105]
 [0.24778761 0.375     ]
 [0.28318584 0.44736842]
 [0.72566372 0.84210526]
 [0.71681416 0.73026316]
 [0.71681416 0.60526316]
 [0.65486726 0.59210526]
 [0.61946903 0.60526316]
 [0.82300885 0.77631579]
 [0.83185841 0.73684211]
 [0.83185841 0.78947368]
 [0.84070796 0.75657895]
 [0.84070796 0.81578947]
 [0.85840708 0.73026316]
 [0.92035398 0.70394737]
 [0.9380531  0.70394737]
 [0.92035398 0.73684211]
 [0.94690265 0.80263158]
 [0.98230088 0.74342105]
 [1.         0.73026316]
 [0.21238938 0.94078947]
 [0.24778761 0.95394737]
 [0.27433628 0.98026316]


In [2]:
from sklearn.neighbors import KNeighborsClassifier					
import pandas as pd 
import numpy as np	

# ASSIGNMENT 1

In [13]:
dataset = pd.read_csv('/Users/farrelmanazilin/Downloads/data/milk.csv')
dataset

pH  Temprature  Taste  Odor  Fat   Turbidity  Colour   Grade
0     6.6          35      1     0     1          0     254    high
1     6.6          36      0     1     0          1     253    high
2     8.5          70      1     1     1          1     246     low
3     9.5          34      1     1     0          1     255     low
4     6.6          37      0     0     0          0     255  medium
...   ...         ...    ...   ...   ...        ...     ...     ...
1054  6.7          45      1     1     0          0     247  medium
1055  6.7          38      1     0     1          0     255    high
1056  3.0          40      1     1     1          1     255     low
1057  6.8          43      1     0     1          0     250    high
1058  8.6          55      0     1     1          1     255     low

[1059 rows x 8 columns]

In [14]:
train_data = np.array(dataset)[ :, :-1]
train_data

array([[6.6, 35, 1, ..., 1, 0, 254],
       [6.6, 36, 0, ..., 0, 1, 253],
       [8.5, 70, 1, ..., 1, 1, 246],
       ...,
       [3.0, 40, 1, ..., 1, 1, 255],
       [6.8, 43, 1, ..., 1, 0, 250],
       [8.6, 55, 0, ..., 1, 1, 255]], dtype=object)

In [15]:
train_label = np.array(dataset)[:, -1]
train_label

array(['high', 'high', 'low', ..., 'low', 'high', 'low'], dtype=object)

# ASSIGNMENT 2

In [16]:
sc = MinMaxScaler(feature_range= (0, 1))
data = sc.fit_transform(train_data) 
print(data)	

[[0.55384615 0.01785714 1.         ... 1.         0.         0.93333333]
 [0.55384615 0.03571429 0.         ... 0.         1.         0.86666667]
 [0.84615385 0.64285714 1.         ... 1.         1.         0.4       ]
 ...
 [0.         0.10714286 1.         ... 1.         1.         1.        ]
 [0.58461538 0.16071429 1.         ... 1.         0.         0.66666667]
 [0.86153846 0.375      0.         ... 1.         1.         1.        ]]


# ASSIGNMENT 3

In [22]:
test_pH = float(input('Masukkan data Ph yang diinginkan(3-9,5) : '))
test_suhu = float(input('Masukkan data suhu yang diinginkan(34C-90C) : '))
test_rasa = float(input('Masukkan data rasa yang diinginkan(0-1) : '))
test_bau = float(input('Masukkan data bau yang diinginkan(0-1) : '))
test_lemak = float(input('Masukkan data lemak yang diinginkan(0-1) : '))
test_kekeruhan = float(input('Masukkan data kekeruhan yang diinginkan(0-1) : '))
test_warna = float(input('Masukkan data warna yang diinginkan(240-255) : '))
test_data= np.array([test_pH,test_suhu,test_rasa,test_bau,test_lemak,test_kekeruhan,test_warna])
print(test_data)	

Masukkan data Ph yang diinginkan(3-9,5) : 5
Masukkan data suhu yang diinginkan(34C-90C) : 36
Masukkan data rasa yang diinginkan(0-1) : 1
Masukkan data bau yang diinginkan(0-1) : 1
Masukkan data lemak yang diinginkan(0-1) : 1
Masukkan data kekeruhan yang diinginkan(0-1) : 1
Masukkan data warna yang diinginkan(240-255) : 251
[  5.  36.   1.   1.   1.   1. 251.]


In [23]:
test_data = np.reshape(test_data, (1, -1))	
sc = MinMaxScaler(feature_range= (0, 1))
data4 = sc.fit_transform(test_data) 
print(data4)

[[0. 0. 0. 0. 0. 0. 0.]]


In [27]:
kNN =KNeighborsClassifier(n_neighbors=3, weights='distance')					
kNN.fit(data, train_label)
hasil= kNN.predict(data4)	
print("Hasil Data Test", data4)
print("Hasil dari k-NN : ", hasil)	

Hasil Data Test [[0. 0. 0. 0. 0. 0. 0.]]
Hasil dari k-NN :  ['medium']


# ASSIGNMENT 4

In [23]:
dataset2 = pd.read_csv('/Users/farrelmanazilin/Downloads/data/milk_training.csv')
dataset2

pH  Temprature  Taste  Odor  Fat  Turbidity  Colour   Grade
0    6.6          35      1     0    1          0     254    high
1    6.6          36      0     1    0          1     253    high
2    6.6          37      1     1    1          1     255    high
3    6.8          45      0     1    1          1     255    high
4    6.6          45      0     1    1          1     250    high
..   ...         ...    ...   ...  ...        ...     ...     ...
737  6.7          45      1     1    1          0     245  medium
738  6.5          38      1     0    1          0     255  medium
739  6.7          41      1     0    0          0     247  medium
740  6.8          41      0     0    0          0     255  medium
741  6.8          38      0     0    0          0     255  medium

[742 rows x 8 columns]

In [28]:
train_data2 = np.array(dataset2)[ :, :-1]
train_data2

array([[35, 1, 0, 1, 0, 254],
       [36, 0, 1, 0, 1, 253],
       [37, 1, 1, 1, 1, 255],
       ...,
       [41, 1, 0, 0, 0, 247],
       [41, 0, 0, 0, 0, 255],
       [38, 0, 0, 0, 0, 255]], dtype=object)

In [44]:
train_label2 = np.array(dataset2)[:, -1]
train_label2

array(['high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
      

# ASSIGNMENT 5

In [29]:
sc = MinMaxScaler(feature_range= (0, 1))
data2 = sc.fit_transform(train_data2) 
print(data2)

[[0.01785714 1.         0.         1.         0.         0.93333333]
 [0.03571429 0.         1.         0.         1.         0.86666667]
 [0.05357143 1.         1.         1.         1.         1.        ]
 ...
 [0.125      1.         0.         0.         0.         0.46666667]
 [0.125      0.         0.         0.         0.         1.        ]
 [0.07142857 0.         0.         0.         0.         1.        ]]


# ASSIGNMENT 6

In [30]:
dataset3 = pd.read_csv('/Users/farrelmanazilin/Downloads/data/milk_testing.csv')
dataset3

pH  Temprature  Taste  Odor  Fat  Turbidity  Colour   Grade
0    6.8          45      1     1    1          0     245    high
1    6.6          37      1     1    1          1     255    high
2    6.7          38      1     0    1          0     255    high
3    6.8          45      0     1    1          1     255    high
4    6.6          37      1     1    1          1     255    high
..   ...         ...    ...   ...  ...        ...     ...     ...
312  6.5          36      0     0    0          0     247  medium
313  6.6          38      0     0    0          0     255  medium
314  6.5          37      0     0    0          0     255  medium
315  6.5          40      1     0    0          0     250  medium
316  6.7          45      1     1    0          0     247  medium

[317 rows x 8 columns]

In [98]:
test_data2 = np.array(dataset3)[ :, :-1]
test_data2

array([[6.8, 45, 1, ..., 1, 0, 245],
       [6.6, 37, 1, ..., 1, 1, 255],
       [6.7, 38, 1, ..., 1, 0, 255],
       ...,
       [6.5, 37, 0, ..., 0, 0, 255],
       [6.5, 40, 1, ..., 0, 0, 250],
       [6.7, 45, 1, ..., 0, 0, 247]], dtype=object)

In [99]:
test_label2 = np.array(dataset3)[:, -1]
test_label2

array(['high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'low', 'low', 'low', 'low',
       'low', 'low', 'low', 'low', 'low', 'low', 'low', 'low', 'low',
       'low', 'low', 'low', 'low', 'low', 'low', 'low', 'low', 'low',
       'low', 'low', 'low', 'low', 'low', 'low', 'low', 'low', 'low',
       'low', 'low', 'low', 'low', 'low', 'low', 'low', 'low', 'low',
      

# ASSIGNMENT 7

In [32]:
sc = MinMaxScaler(feature_range= (0, 1))
data3 = sc.fit_transform(train_data3) 
print(data3)

[[0.19642857 1.         1.         1.         0.         0.33333333]
 [0.05357143 1.         1.         1.         1.         1.        ]
 [0.07142857 1.         0.         1.         0.         1.        ]
 ...
 [0.05357143 0.         0.         0.         0.         1.        ]
 [0.10714286 1.         0.         0.         0.         0.66666667]
 [0.19642857 1.         1.         0.         0.         0.46666667]]


# ASSIGNMENT 8

In [105]:
kNN =KNeighborsClassifier(n_neighbors=1, weights='distance')					
kNN.fit(test_data2, test_label2)
hasil= kNN.predict(test_data2)	
print("Hasil Data Test",test_data2)
print("Hasil dari k-NN : ", hasil)	

Hasil Data Test [[6.8 45 1 ... 1 0 245]
 [6.6 37 1 ... 1 1 255]
 [6.7 38 1 ... 1 0 255]
 ...
 [6.5 37 0 ... 0 0 255]
 [6.5 40 1 ... 0 0 250]
 [6.7 45 1 ... 0 0 247]]
Hasil dari k-NN :  ['high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'low' 'low' 'low' 'low'
 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low'
 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low'
 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low'
 'low' 'low' 'low' 'low' 

In [106]:
kNN =KNeighborsClassifier(n_neighbors=2, weights='distance')					
kNN.fit(test_data2, test_label2)
hasil= kNN.predict(test_data2)	
print("Hasil Data Test",test_data2)
print("Hasil dari k-NN : ", hasil)	

Hasil Data Test [[6.8 45 1 ... 1 0 245]
 [6.6 37 1 ... 1 1 255]
 [6.7 38 1 ... 1 0 255]
 ...
 [6.5 37 0 ... 0 0 255]
 [6.5 40 1 ... 0 0 250]
 [6.7 45 1 ... 0 0 247]]
Hasil dari k-NN :  ['high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'low' 'low' 'low' 'low'
 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low'
 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low'
 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low'
 'low' 'low' 'low' 'low' 

In [107]:
kNN =KNeighborsClassifier(n_neighbors=3, weights='distance')					
kNN.fit(test_data2, test_label2)
hasil= kNN.predict(test_data2)	
print("Hasil Data Test",test_data2)
print("Hasil dari k-NN : ", hasil)	

Hasil Data Test [[6.8 45 1 ... 1 0 245]
 [6.6 37 1 ... 1 1 255]
 [6.7 38 1 ... 1 0 255]
 ...
 [6.5 37 0 ... 0 0 255]
 [6.5 40 1 ... 0 0 250]
 [6.7 45 1 ... 0 0 247]]
Hasil dari k-NN :  ['high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'low' 'low' 'low' 'low'
 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low'
 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low'
 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low'
 'low' 'low' 'low' 'low' 

In [108]:
kNN =KNeighborsClassifier(n_neighbors=4, weights='distance')					
kNN.fit(test_data2, test_label2)
hasil= kNN.predict(test_data2)	
print("Hasil Data Test",test_data2)
print("Hasil dari k-NN : ", hasil)	

Hasil Data Test [[6.8 45 1 ... 1 0 245]
 [6.6 37 1 ... 1 1 255]
 [6.7 38 1 ... 1 0 255]
 ...
 [6.5 37 0 ... 0 0 255]
 [6.5 40 1 ... 0 0 250]
 [6.7 45 1 ... 0 0 247]]
Hasil dari k-NN :  ['high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'low' 'low' 'low' 'low'
 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low'
 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low'
 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low'
 'low' 'low' 'low' 'low' 

In [109]:
kNN =KNeighborsClassifier(n_neighbors=5, weights='distance')					
kNN.fit(test_data2, test_label2)
hasil= kNN.predict(test_data2)	
print("Hasil Data Test",test_data2)
print("Hasil dari k-NN : ", hasil)	

Hasil Data Test [[6.8 45 1 ... 1 0 245]
 [6.6 37 1 ... 1 1 255]
 [6.7 38 1 ... 1 0 255]
 ...
 [6.5 37 0 ... 0 0 255]
 [6.5 40 1 ... 0 0 250]
 [6.7 45 1 ... 0 0 247]]
Hasil dari k-NN :  ['high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'low' 'low' 'low' 'low'
 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low'
 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low'
 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low'
 'low' 'low' 'low' 'low' 